spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12344321
    url: jdbc:mysql://localhost:3306/java_project?useUnicode=true&characterEncoding=UTF-8
    username: root
debug: true